<?xml version="1.0"?>
<package format="3">
  <name>campusbot_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch and configuration package for CampusBot.</description>
  <maintainer email="3265243093@qq.com">wzt</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>campusbot_description</exec_depend>
  <exec_depend>campusbot_navigation</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
