<?xml version="1.0"?>
<package format="3">
  <name>campusbot_task_manager</name>
  <version>0.1.0</version>
  <description>CampusBot navigation task management nodes.</description>
  <maintainer email="3265243093@qq.com">wzt</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
