<?xml version="1.0"?>
<package format="3">
  <name>campusbot_navigation</name>
  <version>0.1.0</version>
  <description>SLAM, localization and Nav2 configuration for CampusBot.</description>
  <maintainer email="3265243093@qq.com">wzt</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_amcl</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
